const PART_1_RAW = [
    { n: 1, q: "I’m taking my sister out as she ___ any sun for a long time.", options: ["hasn’t had", "haven’t had", "hadn’t been", "will have", "shall have"], correct: 0 },
    { n: 2, q: "He ___ ill for three months already.", options: ["was", "has been", "is", "have been", "were"], correct: 1 },
    { n: 3, q: "Who goes sightseeing?", options: ["Nina does.", "We shall.", "We did.", "I did.", "She has."], correct: 0 },
    { n: 4, q: "I usually ___ a blouse and jeans at home, but today I ___ on a new dress.", options: ["wear/have put", "have worn/have put", "wore/has put", "wears/has put", "will wear/put"], correct: 0 },
    { n: 5, q: "What ___ the president ___?-He ___ a contract.", options: ["does/do/has signed", "is/doing/is signing", "will/do/was signing", "is/ going to do/would sign", "shall/do/has been signing"], correct: 1 },
    { n: 6, q: "Look! The cat ___ your cutlet.", options: ["is eating", "was eating", "eats", "has been eating", "had eaten"], correct: 0 },
    { n: 7, q: "You look pale. You ___ too hard these days.", options: ["have been working", "worked", "are working", "work", "were working"], correct: 0 },
    { n: 8, q: "What ___ you ___ since I saw you last?", options: ["do/do", "are/doing", "have/been doing", "did/do", "will/do"], correct: 2 },
    { n: 9, q: "It is 8.30. Ben and Ann ___ breakfast.", options: ["have", "are having", "is having", "was having", "were having"], correct: 1 },
    { n: 10, q: "She ___ a journalist nowadays.", options: ["are", "was", "is", "were", "am"], correct: 2 },
    { n: 11, q: "You ___ always ___ your things. Put them into their bag.", options: ["are/losing", "-/lost", "have/lost", "shall/have been losing", "had/lust"], correct: 0 },
    { n: 12, q: "What place ___ the youth of our country occupy in all branches now?", options: ["did", "shall", "is", "does", "will"], correct: 3 },
    { n: 13, q: "I ___ home for lunch on Mondays. I have lunch in the canteen.", options: ["didn’t go", "was going", "don’t go", "doesn’t go", "will not go"], correct: 2 },
    { n: 14, q: "Westminster Abbey is the ancient old church in which the coronation ceremonies of almost all English kings and queens ___ place.", options: ["will take", "was taken", "was taking", "is taking", "have taken"], correct: 4 },
    { n: 15, q: "This is the most interesting film I ___ ever ___.", options: ["didn’t/see", "was/seen", "have /saw", "have/seen", "had/seen"], correct: 3 },
    { n: 16, q: "“Nobody ___ in that country,” said Pinocchio to his friend.", options: ["don’t learn", "are learning", "learns", "doesn’t learn", "learn"], correct: 2 },
    { n: 17, q: "Paul ___ a student of Cambridge University.", options: ["were", "are", "am", "be", "is"], correct: 4 },
    { n: 18, q: "“Little boy”, said a man, “why do you carry that umbrella over your head? It ___ and the sun ___”", options: ["rains/isn’t shining", "doesn’t rain/shines", "isn’t raining/isn’t shining", "is raining/is shining", "isn’t raining/don’t shine"], correct: 2 },
    { n: 19, q: "Who often has dinner at the canteen?", options: ["I did", "we do", "he had", "they have", "she will"], correct: 1 },
    { n: 20, q: "I ___ never ___ him before.", options: ["- /met", "- /meet", "have/met", "has/met", "-/meets"], correct: 2 },
    { n: 21, q: "The weather is awful, it ___ all day.", options: ["rains", "is raining", "rained", "has rained", "has been raining"], correct: 4 },
    { n: 22, q: "It is 2 o’clock. I ___ afraid I ___ late.", options: ["was/am", "shall be/am", "am/am", "was/was", "am/wasn’t"], correct: 2 },
    { n: 23, q: "Who usually answers these letters in your office?", options: ["My friend can.", "That man will.", "I do, of course.", "Mary is.", "Those engineers did."], correct: 2 },
    { n: 24, q: "The milk is hot I ___ on it to make it cold.", options: ["am blowing", "blow", "is blowing", "blew", "had blown"], correct: 0 },
    { n: 25, q: "- You don’t like horror films, do you?- ___ . They are so terrifying.", options: ["Yes, I can.", "No, I can’t.", "No, I don’t.", "Yes, I do.", "No, we didn’t."], correct: 2 },
    { n: 26, q: "___ this engineer work at the Ministry of Foreign Affairs.", options: ["do", "does", "has", "had", "shall"], correct: 1 },
    { n: 27, q: "He ___ never ___ him sing.", options: ["had___ heard", "has___heard", "have___ heard", "was___ hearing", "is___ hearing"], correct: 1 },
    { n: 28, q: "I think ___ .", options: ["if he is about fifty", "he is about fifty", "her about fifty", "him about fifty", "be about fifty"], correct: 1 },
    { n: 29, q: "I miss her very much, almost every minute of the day I think of her, or I think I ___ her.", options: ["am hearing", "hear", "heard", "have heard", "will hear"], correct: 1 },
    { n: 30, q: "Look! There ___ a man sitting at the first table near the door. He ___ at us.", options: ["was/looks", "had been/looked", "were/had looked", "is/is looking", "is/was looking"], correct: 3 }
];

const PART_2_RAW = [
    { n: 31, q: "These engineers always ___ in the office and ___", options: ["stayed/learn", "stay/learn", "stays/learns", "have stayed/learned", "stay/learned"], correct: 1 },
    { n: 32, q: "It’s the happiest evening I ever ___ .", options: ["had", "have had", "has", "has had", "had had"], correct: 1 },
    { n: 33, q: "Let me show the picture that I ___ this week.", options: ["am drawing", "shall be drawing", "have drawn", "drew", "will be drawing"], correct: 2 },
    { n: 34, q: "This is the 7th year Ann and Mary ___ this school.", options: ["has attended", "have been attending", "had been attending", "are attending", "were attending"], correct: 1 },
    { n: 35, q: "He ___ his English in the morning, he ___ it in the evening.", options: ["doesn’t have/is having", "don’t have/had", "doesn’t have/has", "didn’t have/have", "hadn’t/will have"], correct: 2 },
    { n: 36, q: "The sun ___ in the East and ___ in the West.", options: ["sets/rises", "sets/goes", "rises/sets", "goes/rises", "set/rise"], correct: 2 },
    { n: 37, q: "While ___ to school we always ___ a bus.", options: ["going/take", "went/take", "shall go/will take", "had gone/took", "goes/takes"], correct: 0 },
    { n: 38, q: "We don’t like him because he always ___ lies.", options: ["tell", "was telling", "tells", "are telling", "has told"], correct: 2 },
    { n: 39, q: "I ___ all my work. I am free now.", options: ["do", "am doing", "shall do", "have done", "had done"], correct: 3 },
    { n: 40, q: "She ___ at school since 1984.", options: ["teach", "has been teaching", "taught", "was teaching", "have taught"], correct: 1 },
    { n: 41, q: "- ___ your father ___ at the Medical College?- Yes, he does.", options: ["do/work", "did/work", "has/worked", "does/work", "shall/work"], correct: 3 },
    { n: 42, q: "He ___ to school at 7:30 and ___ at 2 o’clock.", options: ["goes/comes back", "went/is coming back", "go/come back", "was going/has come back", "is going/came back"], correct: 0 },
    { n: 43, q: "-You ___ not ___ your soup.-I’m sorry. I’m not hungry.", options: ["are/eat", "has/eaten", "are/eating", "did/ate", "will/eat"], correct: 2 },
    { n: 44, q: "-Who ___ French in your family?-I ___ .", options: ["speaks/do", "speak/does", "spoke/do", "speaking/did", "are speaking/did"], correct: 0 },
    { n: 45, q: "Although Mary has been cooking for many years, she still ___ how to prepare Chinese food.", options: ["did not know", "know", "don’t know", "doesn’t know", "hadn’t known"], correct: 3 },
    { n: 46, q: "The aims of the course ___ me willing to begin.", options: ["makes", "is making", "were made", "make", "making"], correct: 3 },
    { n: 47, q: "Listen! Somebody ___ in the next room.", options: ["sing", "sings", "are singing", "is singing", "is sung"], correct: 3 },
    { n: 48, q: "-___ life ___ on Mars?-No, it ___ .", options: ["Does/exist/doesn’t", "Did/existed/didn’t", "Has/existed/had", "Had/existed/had", "Will/exist/will"], correct: 0 },
    { n: 49, q: "I ___ this man at all.", options: ["don’t know", "know", "knew", "have known", "doesn’t know"], correct: 0 },
    { n: 50, q: "The boys ___ four English books this year.", options: ["read", "had read", "reads", "have read", "read"], correct: 3 },
    { n: 51, q: "I know he reads every book I ___ ever ___ of.", options: ["-/hear", "-/heard", "have/heard", "has/heard", "had/heard"], correct: 2 },
    { n: 52, q: "Nothing will make him ___ back to her.", options: ["to come", "come", "came", "coming", "would come"], correct: 1 },
    { n: 53, q: "Listen! Someone ___ at the door.", options: ["knocks", "to knock", "has knocked", "is knocking", "has been knocking"], correct: 3 },
    { n: 54, q: "“This thief ___ usually promise to steal again,” said Sherlock Holmes.", options: ["won’t", "didn’t", "isn’t", "doesn’t", "don’t"], correct: 3 },
    { n: 55, q: "Samuel says he’s 25 years old, but nobody ___ him.", options: ["is believing", "believes", "had believed", "don’t believe", "doesn’t believe"], correct: 1 },
    { n: 56, q: "The sea ___ to those who ___ to listen to it.", options: ["speaks/likes", "speak/like", "speaks/like", "speak/likes", "speak/will like"], correct: 2 },
    { n: 57, q: "Take your umbrella. It ___ .", options: ["was raining", "rained", "rains", "is raining", "would be raining"], correct: 3 },
    { n: 58, q: "We can’t disturb him now. He ___ .", options: ["operate", "will operate", "has operated", "is operating", "operates"], correct: 3 },
    { n: 59, q: "The children of the man who works with me ___ the window this morning.", options: ["were broken", "break", "broke", "have broken", "had broken"], correct: 3 },
    { n: 60, q: "“Who ___ this picture?” the teacher asks.", options: ["is drawn", "drawn", "have drawn", "draws", "has drawn"], correct: 4 }
];

const PART_3_RAW = [
    { n: 61, q: "-Where is Comrade A?-He ___ tennis.", options: ["plays", "is playing", "played", "has been playing", "will play"], correct: 1 },
    { n: 62, q: "I ___ never ___ such beautiful flowers before.", options: ["shall / see", "had / seen", "have / seen", "has / seen", "will / see"], correct: 2 },
    { n: 63, q: "I’ve got to get him to the station. His train ___ at the moment.", options: ["leave", "has left", "had left", "is leaving", "are leaving"], correct: 3 },
    { n: 64, q: "-What ___ you ___?-I ___ now.", options: ["are/doing/am washing up", "have/done/am washing up", "have/been done/am washed up", "were/done/have washed up", "is/doing/did not wash up"], correct: 0 },
    { n: 65, q: "We can go out now. It ___ .", options: ["don’t rain", "rains", "didn’t rain", "has rained", "isn’t raining"], correct: 4 },
    { n: 66, q: "You’ll see what I ___ about you recently.", options: ["shall write", "have written", "had written", "is written", "was written"], correct: 1 },
    { n: 67, q: "She ___ since last week.", options: ["is ill", "was ill", "had been ill", "has been ill", "will be ill"], correct: 3 },
    { n: 68, q: "Listen! Somebody ___ at the door.", options: ["knocked", "has knocked", "is knocking", "was knocking", "knocks"], correct: 2 },
    { n: 69, q: "This year we ___ a good harvest of cotton.", options: ["has grown", "have grown", "grown", "were growing", "are grown"], correct: 1 },
    { n: 70, q: "Look at the little boys! They ___ with stones.", options: ["play", "will play", "are playing", "is playing", "played"], correct: 2 },
    { n: 71, q: "It ___ him 20 minutes to get to the work usually.", options: ["take", "is taking", "have taken", "is not taking", "takes"], correct: 4 },
    { n: 72, q: "Usually my working day ___ at 8.30 sharp.", options: ["start", "starts", "would be", "won’t start", "has started"], correct: 1 },
    { n: 73, q: "Stop a minute, think what you ___ .", options: ["are saying", "say", "says", "is saying", "has said"], correct: 0 },
    { n: 74, q: "The population of the world ___ very fast.", options: ["rise", "rises", "is rising", "rose", "is risen"], correct: 2 },
    { n: 75, q: "Tourists ___ a lot of different information when they travel.", options: ["get", "gets", "has got", "would get", "were getting"], correct: 0 },
    { n: 76, q: "The English seaside ___ very popular lately.", options: ["becomes", "has become", "became", "will become", "is becoming"], correct: 1 },
    { n: 77, q: "___ he already___ the rules in the race ?", options: ["did/break", "does/break", "is/breaking", "has/broken", "had/broken"], correct: 3 },
    { n: 78, q: "Peter ___ his lessons. When he finishes them he’ll watch TV.", options: ["does", "do", "did", "is doing", "has done"], correct: 3 },
    { n: 79, q: "I ___ never ___ the book.", options: ["didn’t/read", "haven’t/read", "have/read", "don’t/read", "was/reading"], correct: 2 },
    { n: 80, q: "Look! The girls ___ in the park.", options: ["skate", "skated", "are skating", "will skate", "has skated"], correct: 2 },
    { n: 81, q: "She is sorry, she ___ so rude.", options: ["were", "will be", "are", "has been", "had been"], correct: 3 },
    { n: 82, q: "Why ___ nothing ___?", options: ["has / been done still", "hasn’t / been done yet", "has / been done yet", "was / done yet", "have / been done yet"], correct: 2 },
    { n: 83, q: "Shh! The teacher ___ on the blackboard.", options: ["wrote", "was writing", "writes", "will write", "is writing"], correct: 4 },
    { n: 84, q: "I ___ here since 1972.", options: ["was living", "had lived", "lives", "am living", "have lived"], correct: 4 },
    { n: 85, q: "___ you ___ to England?", options: ["were/being", "are/being", "have/been", "were/being", "had/been"], correct: 2 },
    { n: 86, q: "Hello! Who ___?", options: ["spoke", "speaks", "has been speaking", "is speaking", "was spoken"], correct: 3 },
    { n: 87, q: "Max ___ to be good at interpreting, ___ he?", options: ["doesn’t seem/does", "seems/does", "seemed/did", "seems/does", "didn’t seem/doesn’t"], correct: 0 },
    { n: 88, q: "___ you ever ___ Herr Boschen sing his great German comic songs?", options: ["had/heard", "did/hear", "do/hear", "are/hearing", "have/heard"], correct: 4 },
    { n: 89, q: "Who ___ writing the text yet?", options: ["haven’t finished", "didn’t finish", "doesn’t finish", "won’t finish", "hasn’t finished"], correct: 4 },
    { n: 90, q: "- What ___ you ___?- I ___ a letter.", options: ["are doing/am writing", "have done/am writing", "did/write", "have done/am writing", "has done/wrote"], correct: 0 },
    { n: 91, q: "We ___ already twenty words.", options: ["learned", "have learned", "learn", "will learn", "are learning"], correct: 1 },
    { n: 92, q: "“I can’t marry Mr. Fire. I ___ already ___ my word to another man”, said the chief’s daughter.", options: ["don’t/give", "had/given", "shall/give", "didn’t/give", "have/given"], correct: 4 },
    { n: 93, q: "Be quick! A dog ___ after your child.", options: ["runs", "ran", "was running", "will run", "is running"], correct: 4 },
    { n: 94, q: "I ___ never ___ to the USA.", options: ["is/ been", "has/been", "have/been", "having/been", "was/being"], correct: 2 },
    { n: 95, q: "Oh, not really, I ___ a minute since I came in.", options: ["haven’t had", "haven’t", "were not", "will have", "hadn’t"], correct: 0 },
    { n: 96, q: "Take away the crib; the teacher ___ at you.", options: ["look", "is looking", "looks", "looked", "had looked"], correct: 1 },
    { n: 97, q: "I ___ them for 10 months.", options: ["know", "knows", "have known", "will know", "shall know"], correct: 2 },
    { n: 98, q: "Why ___ you ___ the coat? It’s not cold.", options: ["do/put on", "has/put on", "have/put on", "would/put on", "had/put on"], correct: 2 },
    { n: 99, q: "Don’t enter the classroom. The students ___ an exam.", options: ["write", "were writing", "have written", "are writing", "had been written"], correct: 3 },
    { n: 100, q: "Look! They ___ in our direction.", options: ["come", "came", "will come", "was coming", "are coming"], correct: 4 },
    { n: 101, q: "I ___ Paul since Christmas.", options: ["don’t see", "haven’t seen", "had hadn’t seen", "wasn’t seen", "won’t see"], correct: 1 },
    { n: 102, q: "“Fortune” ___ the magazine of business success for over 50 years.", options: ["is", "was", "will be", "has been", "were"], correct: 3 },
    { n: 103, q: "She ___ false impressions on those who ___ you.", options: ["will produce / hadn’t known", "produces / don’t know", "produces / doesn’t know", "has produced / will not know", "would produce / have not known"], correct: 1 },
    { n: 104, q: "Food prices ___ rapidly in the past few months.", options: ["had risen", "has risen", "have risen", "was rising", "rises"], correct: 2 }
];
