const fs = require('fs');
const path = require('path');

// Generate dictionary.js from dictionary.json
function generateDictJS() {
    const projectRoot = path.join(__dirname, '..');
    const jsonPath = path.join(projectRoot, 'data', 'dictionary.json');
    const jsPath = path.join(projectRoot, 'dictionary.js');

    console.log('📝 Generating dictionary.js from dictionary.json...\n');

    if (!fs.existsSync(jsonPath)) {
        console.error('❌ Error: dictionary.json not found!');
        console.log('Run "npm run translate" first to create the dictionary.');
        process.exit(1);
    }

    const dictionary = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
    const wordCount = Object.keys(dictionary).length;

    // Load grammar info if it exists
    const grammarPath = path.join(projectRoot, 'data', 'grammar_info.json');
    let grammarInfo = {};
    if (fs.existsSync(grammarPath)) {
        grammarInfo = JSON.parse(fs.readFileSync(grammarPath, 'utf-8'));
    }

    // Generate JavaScript file with window globals
    const jsContent = `// Auto-generated from dictionary.json
// DO NOT EDIT THIS FILE MANUALLY
// To update translations, edit data/dictionary.json and run: npm run build:dict

window.UZ_DICT = ${JSON.stringify(dictionary, null, 4)};

window.GRAMMAR_INFO = ${JSON.stringify(grammarInfo, null, 4)};
`;

    fs.writeFileSync(jsPath, jsContent);

    console.log(`✅ Generated dictionary.js with ${wordCount} words and ${Object.keys(grammarInfo).length} grammar entries`);
    console.log(`📍 Location: ${jsPath}\n`);
}

// Run if called directly
if (require.main === module) {
    generateDictJS();
}

module.exports = { generateDictJS };
